### ISSUE TITLE
use_testdata_raw should have the same interface and similar functionality to usethis::use_data_raw

### ISSUE THREAD

**Issue by TylerGrantSmith** [s-fleck/testthis#15]
I think it would be good for `use_testdata_raw` to create the raw script file, not just the directory.

**Comment by s-fleck** [comment]
you're probably right, I'll change it next time I work on testthis.

**Comment by s-fleck** [comment]
fixed. Behaves similar to `usethis::use_data()` now if the argument `name` is provided, but continues to create an empty directory if no name is provided (as opposed to `usethis::use_data()` which creates an IMHO annoying dummy file)
