### ISSUE TITLE
usethis release makes a test fail

### ISSUE THREAD

**Issue by jennybc** [s-fleck/testthis#16]
We are in the process of releasing usethis v1.6.0.

Although we did not see a problem with testthis in our revdep checks, CRAN did. It appears to be due to a brittle test that relies on usethis's user-facing messaging.

I suspect it's due to https://github.com/r-lib/usethis/commit/7af1aa2e0ac0b699fdd39f5cfbe4d1ccba41bc48, where we "Use messages rather than cat to output".

Below is what CRAN's auto-check service shows.

Can you rework your test to pass against dev usethis? I don't think this will hold up the usethis release, but let's fix it soon-ish anyway. Ideally your tests wouldn't rely on, e.g., the exact behaviour of another package re: messaging.

---

Package: testthis
Check: tests
New result: ERROR
    Running â€˜testthat.Râ€™ [2s/2s]
  Running the tests in â€˜tests/testthat.Râ€™ failed.
  Complete output:
    > library(testthat)
    > 
    > test_check("testthis")
    Loading required package: testthis
    âœ” Setting active project to '<no active project>'
    â”€â”€ 1. Failure: use_testdata creates testdata dir (@test_infrastructure.R#54)  â”€â”€
    `expect_message(use_testdata(iris), "You can save data files for tests via")` produced no output
    
    â”€â”€ 2. Failure: use_testdata creates testdata dir (@test_infrastructure.R#62)  â”€â”€
    `expect_message(use_testdata(iris, subdir = "iris"), "You can save data files for tests via")` produced no output
    
    â”€â”€ 3. Failure: use_test_subdir works as expected (@test_infrastructure.R#130)  â”€
    `expect_message(...)` produced no output
    
    â”€â”€ 4. Failure: use_test_subdir works as expected (@test_infrastructure.R#149)  â”€
    `expect_true(use_integration_tests())` produced no output
    
    â”€â”€ 5. Failure: use_test_subdir works as expected (@test_infrastructure.R#154)  â”€
    `expect_true(use_acceptance_tests())` produced no output
    
    â”€â”€ 6. Failure: use_test_subdir works as expected (@test_infrastructure.R#159)  â”€
    `expect_true(use_manual_tests())` produced no output
    
    âœ” Setting active project to '<no active project>'
    â”€â”€ 7. Failure: use_testdata_raw works (@test_use_testdata.R#64)  â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    `use_testdata_raw()` produced no output
    
    âœ” Setting active project to '<no active project>'
    â•â• testthat results  â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
    [ OK: 67 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 7 ]
    1. Failure: use_testdata creates testdata dir (@test_infrastructure.R#54) 
    2. Failure: use_testdata creates testdata dir (@test_infrastructure.R#62) 
    3. Failure: use_test_subdir works as expected (@test_infrastructure.R#130) 
    4. Failure: use_test_subdir works as expected (@test_infrastructure.R#149) 
    5. Failure: use_test_subdir works as expected (@test_infrastructure.R#154) 
    6. Failure: use_test_subdir works as expected (@test_infrastructure.R#159) 
    7. Failure: use_testdata_raw works (@test_use_testdata.R#64) 
    
    Error: testthat unit tests failed
    Execution halted

**Comment by s-fleck** [comment]
Thanks! Fixed in dev and will soon be on its way to cran
