### ISSUE TITLE
specify use_testdata() file names

### ISSUE THREAD

**Issue by harvey131** [s-fleck/testthis#17]
Is it possible to specify the name of a file in use_testdata() to be something other than the object name?  For example if you're generating test data in a for loop and you want to name the file specifically for each loop.

**Comment by s-fleck** [comment]
`use_testdata()` is just a very specific helper for the situation where you want to save an object with its name and do minimal typing. If you want to create test data from a loop, you can just do something like:

```
for (l in LETTERS){
  saveRDS(l, testthis::find_testdata(paste0(l, ".rds")))
}
```

**Comment by harvey131** [comment]
Ok thanks.  From the documentation, it wasn't clear that the "..." argument to testthis::find_testdata can be used to make the file path to read.  The documentation seems to be written for use_testdata()

**Comment by s-fleck** [comment]
Right, the doc is a bit confusing. The differences between the functions are documented  in the `value` section further down. I also found a typo in the documentation of `find_testdata()`. Maybe i need to rework that doc at some point ;)
