### ISSUE TITLE
Missing or unexported object: ‘devtools::parse_ns_file’

### ISSUE THREAD

**Issue by jennybc** [s-fleck/testthis#9]
This is just a heads up. I'm about to submit usethis to CRAN, so I checked this package. I have dev devtools installed and I got this NOTE:

❯ checking dependencies in R code ... NOTE
  Missing or unexported object: ‘devtools::parse_ns_file’

I think your package is fine with CRAN devtools, but this NOTE is heading your way next time devtools runs revdep checks ....

**Comment by s-fleck** [comment]
Thanks for the heads up. Seems the function moved to the package **pkgload**. Should be an easy fix.
